#!/bin/bash

# script to build manylinux wheels inside container
# From: https://github.com/pypa/python-manylinux-demo/blob/master/travis/build-wheels.sh

set -e

# env variables
PLAT="manylinux2014_x86_64"

function repair_wheel {
	wheel="$1"
	if ! auditwheel show "$wheel"; then
		echo "Skipping non-platform wheel $wheel"
	else
		auditwheel repair "$wheel" --plat "$PLAT" -w wheelhouse/
	fi
}

# Remove python3.5 as not supported
rm -rf /opt/python/cp35*

cd build/python/
mkdir -p wheelhouse

# Build each wheel
for PYBIN in /opt/python/*/bin; do
	"${PYBIN}/pip" install -r ../../python/requirements.dev.txt
	"${PYBIN}/python3" setup.py sdist bdist_wheel
done

# Bundle external shared libraries into the wheels
for whl in dist/*.whl; do
	repair_wheel "$whl"
done

# Install packages and test
for PYBIN in /opt/python/*/bin; do
	"${PYBIN}/pip" install cspy --no-index -f wheelhouse/
	"${PYBIN}/python3" -m unittest discover -s ../../test/python/
done
