#!/bin/sh

# script to run tests inside docker containers

set -e

cd /root/

# Clear contents of build dir
if $BUILD_CLEAN
then
	echo "Cleaning build directory"
	rm -rf build/*
fi

# Configure using environment variables set in docker-compose / Dockerfile
cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON \
	-DBUILD_PYTHON=${BUILD_PYTHON} -DBUILD_SHARED_LIBS=${BUILD_PYTHON} \
	-DBENCHMARK_TESTS=${BENCHMARK_TESTS}

cmake --build build --config Release --target all -v

if $BUILD_RELEASE
then
	echo "Building Python manylinux wheels for release"
	./build_manylinux_wheels
else
	# Run tests
	cd build && ctest --verbose
fi
