name: Docs

on:
  push:
    branches: [ master ]

jobs:

  build_docs_job:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:

    - name: Prereqs
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
      run: |
        apt-get update
        apt-get install -y git
        git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" ${GITHUB_REPOSITORY}
      shell: bash

    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}
      run: |
        cd ${GITHUB_REPOSITORY}
        ./docs/build_docs.sh
      shell: bash
