name: Ubuntu docs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
  release:
    types:
      - published

jobs:
  notebooks:
    name: "Upload docs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install LEMON
        run: |
          cp tools/docker/scripts/install_lemon .
          chmod u+x install_lemon
          sudo ./install_lemon
      - name: Configure
        run: cmake -S . -Bbuild -DBUILD_TESTING=ON -DBUILD_PYTHON=ON -DBUILD_SHARED_LIBS=ON
      - name: Install rtds-action
        run: python3 -m pip install rtds-action
      - name: Build
        run: cmake --build build --config Release --target all -v
      - name: Test
        run: cd build && ctest --verbose -R python_unittest
      - name: Install
        run: cmake --build build --config Release --target install -v -- DESTDIR=install
      - name: Group python package
        run: |
          mkdir cspy_docs
          mv build/python/cspy/ cspy_docs/
          mv build/python/setup.py cspy_docs/
      - uses: actions/upload-artifact@v2
        with:
          name: package-for-${{ github.sha }}
          path: cspy_docs/
      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTDS_WEBHOOK_URL }}
          webhook_token: ${{ secrets.RTDS_WEBHOOK_TOKEN }}
          commit_ref: ${{ github.ref }}
