name: Windows Cpp

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install SWIG 4.0.2
      run: |
        (New-Object System.Net.WebClient).DownloadFile("http://prdownloads.sourceforge.net/swig/swigwin-4.0.2.zip","swigwin-4.0.2.zip");
        Expand-Archive .\swigwin-4.0.2.zip .;
        echo "$((Get-Item .).FullName)/swigwin-4.0.2" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Install LEMON 1.3.1
      run: |
        (New-Object System.Net.WebClient).DownloadFile("http://lemon.cs.elte.hu/pub/sources/lemon-1.3.1.zip","lemon-1.3.1.zip");
        Expand-Archive .\lemon-1.3.1.zip .;
        cd lemon-1.3.1;
        cmake -S. -Bbuild -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DLEMON_ENABLE_GLPK=NO -DLEMON_ENABLE_COIN=NO -DLEMON_ENABLE_ILOG=NO;
        cmake --build build --config Release --target ALL_BUILD -- /verbosity:normal /maxcpucounte;
        cmake --build build --config Release --target INSTALL -- /verbosity:normal /maxcpucount
    - name: Check swig
      run: swig -version
    - name: Check cmake
      run: cmake --version
    - name: Configure
      run: cmake -S. -Bbuild -G "Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DBUILD_PYTHON=OFF
    - name: Build
      run: cmake --build build --config Release --target ALL_BUILD -- /verbosity:normal /maxcpucount
    - name: Test
      run: cmake --build build --config Release --target RUN_TESTS -- /verbosity:normal /maxcpucount
    - name: Install
      run: cmake --build build --config Release --target INSTALL -- /verbosity:normal /maxcpucount
